### ISSUE TITLE
all files ended with "tevo/keys.env.dart" got an error

### ISSUE THREAD

**Issue by dextermax3** [yatendra2001/Tevo#48]
hello,
thanks for this great app :)
i got below error once i open the project:
Target of URI doesn't exist: 'package:tevo/keys.env.dart''.
Try running the generator that will generate the file referenced by the URI.dart
( i tried flutter clean>>>>flutter pub get) but still not working
![tevoerrr](https://user-images.githubusercontent.com/105817000/221350217-2df4fbbf-5a10-4e4f-81b8-5e9b2e01b454.jpg)

**Comment by yatendra2001** [comment]
hey @dextermax3 , thanks :)

Actually, you need to create a dart file name "keys.env.dart" under tevo and you need to get an API key from https://getstream.io/chat/


Define that key as streamChatApiKeyProd. And it will run.

Let me know if you need any help further.

**Comment by dextermax3** [comment]
@yatendra2001 worked :)
many thanks

**Comment by yatendra2001** [comment]
Welcome @dextermax3, So  can I close this issue now?

**Comment by dextermax3** [comment]
@yatendra2001
 yup

**Comment by yatendra2001** [comment]
If anyone else also faces same issue, kindly checkout above comments
