### ISSUE TITLE
':webcrypto:externalNativeBuildDebug

### ISSUE THREAD

**Issue by dextermax3** [yatendra2001/Tevo#49]
@yatendra2001 
i got below error which makes me delete "chat_encryption.dart"
and delete "webcrypto" dependence from "pubspec.yaml" file
then the app run fine and i have a progress indicator at start(when following users) and can't create new task
![tevoerrroo](https://user-images.githubusercontent.com/105817000/221355520-b5783583-fbc5-4962-810f-3d22299950aa.jpg)

**Comment by yatendra2001** [comment]
Yeah just remove them, We were thinking of integrating end to end chat encryption but then dropped the idea as StreamChat is already quite secured.
