### ISSUE TITLE
firebase build

### ISSUE THREAD

**Issue by dextermax3** [yatendra2001/Tevo#50]
@yatendra2001 
can i have a screen shot of your firebase? because i cant create task
below is my firebase build
![tevo app](https://user-images.githubusercontent.com/105817000/221356236-db757229-7598-4f4a-81f7-939e00a809ef.jpg)

**Comment by yatendra2001** [comment]
Would you share the specific error that you're getting?

**Comment by dextermax3** [comment]
@yatendra2001 
i have solved the error
it was about creating new indexes ! as below
many thanks bro for your help, appreciate your time and prompt replys 
![tevo app2](https://user-images.githubusercontent.com/105817000/221370872-c6159432-8a61-4896-9d4f-bbe48005506b.jpg)

**Comment by yatendra2001** [comment]
Awesome @dextermax3
